import { 
  SERVER_ERROR, LOGIN_ERROR, USERNAME_ERROR, EMAIL_ERROR, 
  MOBILE_ERROR, PASSWORD_ERROR 
} from './errors';
import { EMAIL_REGEXP, NAME_REGEXP, MOBILE_REGEXP } from './regexps';

export {
  SERVER_ERROR,
  LOGIN_ERROR,
  USERNAME_ERROR,
  EMAIL_ERROR,
  MOBILE_ERROR,
  PASSWORD_ERROR,
  EMAIL_REGEXP,
  NAME_REGEXP,
  MOBILE_REGEXP
}